name: simple_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7	0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.2
  

  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.0
  font_awesome_flutter: 8.8.1
  auto_size_text: ^2.1.0
  flutter_tindercard: ^0.1.8
  fancy_bottom_navigation: ^0.3.2
  responsive_builder: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true

  assets:
    - images/dp.png  
    - images/a1.jpg
    - images/a5.jfif
    - images/d2.jpg
    - images/do3.jfif
    - images/do6.png
    - images/do7.png
    - images/do8.png
    - images/do9.png
    
  # - animations/dpbg.flr
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
     
    - family: DancingScript
      fonts:
        - asset: fonts/DS-B.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"
